export const comprehensiveResources = [
  // articles
  {
    id: 1,
    title: 'Understanding Anxiety: A Complete Guide',
    description: 'Learn about anxiety disorders, symptoms, and evidence-based coping strategies for daily life.',
    type: 'article',
    category: 'Mental Health Basics',
    duration: '10 min read',
    author: 'Dr. Sarah Mitchell, Clinical Psychologist',
    date: 'Jan 15, 2025',
    featured: true,
    image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800',
  },
  {
    id: 2,
    title: 'Depression: Signs, Symptoms & Treatment Options',
    description: 'Comprehensive overview of depression, from recognizing symptoms to exploring treatment paths.',
    type: 'article',
    category: 'Mental Health Basics',
    duration: '12 min read',
    author: 'Dr. James Chen, Psychiatrist',
    date: 'Jan 12, 2025',
    featured: true,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800',
  },
  {
    id: 3,
    title: 'Breaking the Stigma Around Mental Health',
    description: 'Why open conversations about mental health help individuals and communities heal.',
    type: 'article',
    category: 'Awareness',
    duration: '8 min read',
    author: 'Dr. Emily Carter',
    date: 'Jan 20, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
  },
  {
    id: 4,
    title: 'The Mind-Body Connection: How Exercise Improves Mental Health',
    description: 'Discover the science behind how physical activity directly impacts mood and anxiety.',
    type: 'article',
    category: 'Wellness',
    duration: '9 min read',
    author: 'Dr. Raj Patel',
    date: 'Jan 18, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800',
  },

  // videos
  {
    id: 5,
    title: '5-Minute Guided Meditation for Anxiety Relief',
    description: 'Follow along with this calming guided meditation designed to reduce anxiety and center your mind.',
    type: 'video',
    category: 'Mindfulness',
    duration: '5 min',
    author: 'Lumina Wellness Team',
    date: 'Jan 22, 2025',
    featured: true,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
  },
  {
    id: 6,
    title: 'Understanding Cognitive Behavioral Therapy (CBT)',
    description: 'Learn how CBT works and how it can help reframe negative thought patterns.',
    type: 'video',
    category: 'Therapy Basics',
    duration: '12 min',
    author: 'Dr. Lisa Rodriguez, Therapist',
    date: 'Jan 10, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
  },
  {
    id: 7,
    title: 'Sleep Hygiene: Better Sleep for Better Mental Health',
    description: 'Practical tips for improving sleep quality and its profound impact on emotional well-being.',
    type: 'video',
    category: 'Wellness',
    duration: '8 min',
    author: 'Sleep & Wellness Institute',
    date: 'Jan 8, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
  },

  // exercises
  {
    id: 8,
    title: 'Breathing Exercises: Box Breathing Technique',
    description: 'Practice the 4-4-4-4 box breathing method used by Navy SEALs to manage stress.',
    type: 'exercise',
    category: 'Coping Skills',
    duration: '10 min practice',
    author: 'Lumina Wellness Team',
    date: 'Jan 25, 2025',
    featured: true,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
  },
  {
    id: 9,
    title: 'Journaling for Mental Clarity',
    description: 'Structured prompts to help process emotions and gain insight through reflective writing.',
    type: 'exercise',
    category: 'Self-Care',
    duration: '15 min',
    author: 'Dr. Amanda Foster',
    date: 'Jan 17, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800',
  },
  {
    id: 10,
    title: 'Progressive Muscle Relaxation Guide',
    description: 'Step-by-step exercise to release physical tension and calm your nervous system.',
    type: 'exercise',
    category: 'Stress Management',
    duration: '20 min',
    author: 'Relaxation Institute',
    date: 'Jan 14, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
  },

  // audio guides
  {
    id: 11,
    title: 'Sleep Meditation: Guided Body Scan',
    description: 'Gentle audio guide to help you relax deeply and fall asleep peacefully.',
    type: 'audio',
    category: 'Sleep & Relaxation',
    duration: '25 min',
    author: 'Calm Mind Audio',
    date: 'Jan 11, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
  },
  {
    id: 12,
    title: 'Mindfulness for Beginners: Introduction',
    description: 'Start your mindfulness journey with this accessible introduction to present-moment awareness.',
    type: 'audio',
    category: 'Mindfulness',
    duration: '12 min',
    author: 'Mindful Living Collective',
    date: 'Jan 5, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?w=800',
  },

  // additional articles
  {
    id: 13,
    title: 'Managing Stress in College: A Student Guide',
    description: 'Practical strategies for handling academic pressure, social challenges, and self-care.',
    type: 'article',
    category: 'Student Wellness',
    duration: '11 min read',
    author: 'Dr. Michael Torres',
    date: 'Jan 3, 2025',
    featured: false,
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
  },
  {
    id: 14,
    title: 'Building Healthy Boundaries in Relationships',
    description: 'Learn to set and maintain boundaries that protect your mental health and well-being.',
    type: 'article',
    category: 'Relationships',
    duration: '10 min read',
    author: 'Dr. Rachel Kim',
    date: 'Dec 28, 2024',
    featured: false,
    image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800',
  },
  {
    id: 15,
    title: 'Self-Compassion: Treating Yourself with Kindness',
    description: 'Explore the transformative power of self-compassion in mental health recovery.',
    type: 'article',
    category: 'Self-Care',
    duration: '9 min read',
    author: 'Dr. Kristin Williams',
    date: 'Dec 22, 2024',
    featured: false,
    image: 'https://images.unsplash.com/photo-1499728603263-13726abce5fd?w=800',
  },
];

export const resourceCategories = [
  'All',
  'Mental Health Basics',
  'Mindfulness',
  'Therapy Basics',
  'Coping Skills',
  'Self-Care',
  'Wellness',
  'Stress Management',
  'Awareness',
  'Student Wellness',
  'Relationships',
  'Sleep & Relaxation',
];
